In [4]:
import numpy as np

In [26]:
N = 10

In [27]:
# создание numpy array с элементами от числа N до 0

x = np.arange(N-1, -1, -1)

print(x)

[9 8 7 6 5 4 3 2 1 0]


In [28]:
# создание диагональной матрицы с элементами от N до 0

y = np.diag(np.arange(N-1, -1, -1), k=0)

print(y)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [33]:
# сумма элементов диагональной матрицы

y.trace()

45

### Решение системы уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [34]:
# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# значения в правой части уравнения
b = np.array( [4, 12, -3] )

In [35]:
from numpy import linalg

In [53]:
# решение

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [37]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задача 4 домашнего задания

In [38]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [39]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [41]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [42]:
user = np.array([2, 1, 0, 0, 0, 0])

In [52]:
# Нахождение самого похожего пользователя. 
# Т. е. где самое большое косинусное сходство между этим пользователем и пользователями из массива user_stats

user_most_matching = 0
cos = 0

for user in users_stats:    
    if cos < cosine(user, next_user_stats):
        cos = cosine(user, next_user_stats)
        user_most_matching = user
        
    
print(user_most_matching)

[0 1 1 0 0 0]
